apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-live
spec:
  selector:
    matchLabels:
      app: backend-live
  template:
    metadata:
      labels:
        app: backend-live
    spec:
      containers:
      - name: backend-live
        image: yagolopesm/live:3.0
        ports:
        - containerPort: 5000
